n = input('Digite algo: ')
print('O tipo primitivo de n é: {}' .format(type(n)))
print('n é numérico?', n.isnumeric())
print('n é composto só de letras?', n.isalpha())
print('n é alfanumérico?', n.isalnum())
print('n é composto só de maiúsculas?', n.isupper())
print('n é composto só de minúsculas?', n.islower())
print('n está capitalizado?', n.istitle())
print('n é composto só de espaços?', n.isspace())
