frase = 'Curso em Vídeo Python'

print(frase[0:14])
print(frase[:14])
print(frase[15:])
print(frase[9::2])
print(frase.count('o'))
print(frase.count('o', 0, 14))
print(frase.find('deo'))
print(frase.find('Android'))
print('Curso' in frase)
print(frase.replace('Python','Android'))
print(frase)
frase2 = frase.replace('Python','Android')
print(frase2)
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
print(len(frase))
print(frase.strip())
print(frase.rstrip())
print(frase.lstrip())
print(frase.split())
print(frase.upper().count('O'))
frase3 = '   Curso em Vídeo Python   '
print(len(frase3))
print(len(frase3.strip()))
print(frase.lower().find('vídeo'))
frase4 = frase.split()
print(frase4)
frase5 = '-'.join(frase4)
print(frase5)
frase6 = ' '.join(frase4)
print(frase6)
print(frase4[0])
print(frase4[2][3])